apiVersion: v1
kind: Secret
metadata:
  name: my-java-secret
  namespace: production
type: Opaque
data:
  USERNAME: cHJvZHVjdGlvbgo=
  PASSWORD: cHJvZHVjdGlvbkAxMjMK

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-java-config
  namespace: production
data:
  HOSTNAME: mongo-service
