apiVersion: v1
kind: Service
metadata:
  name: my-webapp-service
  namespace: test
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 809
      targetPort: 8080
      nodePort: 30081
